apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: etcd-druid-role-manager
subjects:
- kind: ServiceAccount
  name: etcd-druid
  namespace: default
roleRef:
  kind: ClusterRole
  name: role-manager
  apiGroup: rbac.authorization.k8s.io
