apiVersion: v1
kind: Pod
metadata:
  name: resource-hog
spec:
  nodeSelector:
    kubernetes.io/hostname: job-test-worker
  restartPolicy: Never
  containers:
  - name: stress-container
    image: progrium/stress
    resources:
      requests:
        memory: "1Gi"
        cpu: "1"
      limits:
        memory: "2Gi"
        cpu: "2"
    command: ["stress", "--vm", "2", "--vm-bytes", "1G", "--cpu", "2"]
